<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>EngineFramework.Simulation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../EngineFramework.Core/EngineFramework.Core.csproj" />
    <ProjectReference Include="../EngineFramework.Math/EngineFramework.Math.csproj" />
    <ProjectReference Include="../EngineFramework.Space/EngineFramework.Space.csproj" />
  </ItemGroup>
</Project>
